### ISSUE TITLE
Search Defaults To Current Version

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-io/spring-reference#1]
If you switch versions of the documentation and then search for something it shows results for the current version.

I can see a case where I am using a specific version, search for something and it shows a result for something that is only available in the current version, not the version I am using, and it leads me down a frustrating rabbit hole.  

IMO search should return results for the current version of docs selected.  An added bonus would be if the user had the option to search across all versions if they wanted to.  Or maybe if no results come back they get the option to then search the current version.

**Comment by rwinch** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/issues/11279
